# ==============================================================================
# Mathigon Studio Default Settings
# (c) Mathigon
# ==============================================================================


siteName: Mathigon Studio
privacyURL: https://mathigon.org/policies
banner: (c) Mathigon
locales: [en]

contentDir: content

search:
  enabled: true

sitemap: []

header:
  logo: images/logo.svg
  title: images/title.svg
  links: []

social: {}

footer:
  rows: []
  copyright: Â© Mathigon, 2022

courses:
  revealAll: false
  audio: false

accounts:
  enabled: false
  teachers: false
  parents: false
  restricted: false

tutor:
  enabled: true
  name: Archie
  icon: images/archie.svg
