siteName: Mathigon
description: A interactive textbook
domain: mathigon.org

privacyURL: /policies
googleAnalytics: UA-XXX-XXX
banner: (c) Mathigon Ltd
locales: [en, de, es, fr]

search:
  enabled: true
  popular: ['course:science:optics', 'course:geography:hydrology']

# All custom (non-course) URLs to add to the sitemap
sitemap: [/courses, /custom]

header:
  # File paths are relative to frontend/assets
  logo: images/logo.svg
  title: images/title.svg
  links:
    - title: Courses
      icon: library
      url: /courses

footer:
  rows:
    - links:
        - title: About
          url: /about
        - title: Courses
          url: /courses
  copyright: Â© Mathigon, 2021

social:
  facebook:
    page: Mathigon
    appId: 522356201246169
  twitter:
    handle: MathigonOrg
  instagram:
    handle: mathigon_org
  youtube:
    channel: Mathigon

courses:
  # Reveal all steps at once, even if they have not all been completed.
  revealAll: false

tutor:
  enabled: true
  name: Archie
