siteName: Mathigon
description: A interactive textbook
domain: mathigon.org

privacyURL: /policies
googleAnalytics: UA-XXX-XXX
banner: (c) Mathigon Ltd
locales: [en, de, es, fr]

search:
  enabled: true
  popular: ['course:science:optics', 'course:geography:hydrology']

# All custom (non-course) URLs to add to the sitemap
sitemap: [/courses, /custom]

header:
  # File paths are relative to frontend/assets
  logo: images/logo.svg
  title: images/title.svg
  links:
    - title: Courses
      icon: library
      url: /courses

footer:
  rows:
    - links:
        - title: About
          url: /about
        - title: Courses
          url: /courses
  copyright: Â© Mathigon, 2021

social:
  facebook:
    page: Mathigon
    appId: 522356201246169
  twitter:
    handle: MathigonOrg
  instagram:
    handle: mathigon_org
  youtube:
    channel: Mathigon

accounts:
  enabled: true
  minAge: 13
  privacyPolicy: https://mathigon.org/policies
  termsOfUse: https://mathigon.org/policies#terms
  address: 7 Albert Buildings, 49 Queen Victoria Street, London, United Kingdom, EC4N 4SA
  supportEmail: support@mathigon.org
  cronNotificationsEmail: admin@mathigon.org
  sendgridKey: SG.12345
  mongoServer: mongodb://localhost:27017/mathigon1
  oAuth:
    google:
      key: 1
      secret: 1
    facebook:
      key: 1
      secret: 1

courses:
  revealAll: true  # Reveal all steps at once, even if they have not all been completed
  audio: false  # Generate audio narrations

tutor:
  enabled: true
  name: Archie
